---
- name: Install Java, Git, Mysql-client and Docker on servers
  hosts: servers
  become: yes
  tasks:

    - name: Update all packages (yum equivalent to 'yum update -y')
      yum:
        name: '*'
        state: latest

    - name: Install Java 17
      dnf:
        name: java-17-amazon-corretto-devel
        state: present

    - name: Install Git
      dnf:
        name: git
        state: present

    - name: Install MySQL client
      dnf:
        name: mariadb105
        state: present

    - name: Install Docker
      dnf:
        name: docker
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to the docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Restart Docker service
      systemd:
        name: docker
        state: restarted

    - name: Change ownership of /var/run/docker.sock
      file:
        path: /var/run/docker.sock
        owner: root
        group: docker
        
    - name: Install MySQL client (mariadb105)
      yum:
        name: mariadb105
        state: present

- name: Install Docker Compose on servers
  hosts: servers
  become: yes
  tasks:
    - name: Download Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: '0755'
